PR for Code Review - Calculator UI
wickathou/math-magicians-react-calculator pull request #3
Opened 2023-02-14 22:47 UTC by wickathou

In this PR, the starting design of the calculator is implemented using React

**Features**
- Base structure for calculator
- Use of React functional components and props

**[Live view](https://wickathou.github.io/math-magicians-react-calculator/)**

2023-02-14 23:13 UTC, Omar-Muhamad requested changes
# Changes Required ♻️
### Hi @wickathou,

Nice job, you are almost there.

![](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- You used the correct workflow.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] Please check the inline comments below.

## [Optional] suggestions:

- [ ] Please check the inline comments below.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-02-14 23:13 UTC, Omar-Muhamad commented on src/components/Calculator.js
> +  const calculatorStyle = 'grid grid-cols-4 w-80 h-80 box-border border-4 border-neutral-400';
- [ ] [Optional] It would be better professionally if you style your components using `css module` method instead of what you used here.

2023-02-14 23:13 UTC, Omar-Muhamad commented on src/components/Calculator.js
> +
- [ ] As per this [requirement](https://github.com/microverseinc/curriculum-react-redux/blob/main/math-magicians/project_components.md#:~:text=Calculator.js%20file.-,In%20Calculator.js%2C%20create%20a%20React%20component%20that%20matches%20this%20design%3A,-Implement%20the%20design), Please replace the divide symbol you added `/` with this symbol `÷` instead to match the given design.

| Given Design  | Your Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/68796232/218836370-5286a6b0-3103-4941-aea2-12914937bb0e.png)  | ![image](https://user-images.githubusercontent.com/68796232/218883760-02e32afc-a69b-45a9-9a2e-2169c172decf.png) |

2023-02-15 08:30 UTC, Olamarx approved these changes
Hi @wickathou, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media2.giphy.com/media/xT8qBepJQzUjXpeWU8/giphy.gif"/>
## Highlights
- Linters passed ✔️ 
- functional components
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-15 09:35 UTC, merged